### ISSUE TITLE
drush updb hangs

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/drush#10]
using `drush updb` to run update hooks hangs.
- write an update hook
- run `drush updb`
- check your processes; the php process runs away with ~100% cpu and hangs.

:(

**Comment by dboulet** [comment]
I’m seeing this exact same issue. I have `drush updb -y` in my deployment script, when there is a pending update the deployment never completes and CPU usage on the server skyrockets.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/drush/commit/2e7cf19f302171e633561579c844466f153c86a1.

The problem was that for some reason `system` module was always added into the list of updates to be executed. But if system.module didn't have any updates, then Backdrop would get stuck in an infinite loop trying to determine what update dependencies were needed. Removing this empty array of updates prevents the dependency loop from getting hung up.
