### ISSUE TITLE
Introduce a new `drush_colorize_output()` function, to help consistently add color to output text.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/drush#220]
This came up in #218:

> ...perhaps we should introduce a `drush_colorize_output($output, $color)` function to be re-used in other places?

**Comment by serundeputy** [comment]
thanks @klonos !
PR: https://github.com/backdrop-contrib/backdrop-drush-extension/pull/221

Added a `drush_chalk(string $output, string $color)` to format pieces of output strings.

I went with `drush_chalk` because it is not just color it can make text bold and anything you can do with trerminal formatting.

Here is an example:

![image](https://user-images.githubusercontent.com/6763671/79053203-7bb17a00-7c09-11ea-9fb3-2672a1705064.png)

**Comment by serundeputy** [comment]
Merged. this will ship w/ `1.4.0`.
