### ISSUE TITLE
Generate boilerplate code for module developers.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/drush#32]
Generate:
- `my_module.info`
- `my_module.module`

files from prompts for:
- Module name
- Module description
- Package (optional)

use:
  `drush bp module` ==> spin up module

**Comment by jenlampton** [comment]
There isn't a lot of boilerplate code in Backdrop. It might be nice to have the files created on disk, but what code did you want to put in the .module file? 

I would hate to see a handful of modules implementing unnecessary hooks because the boilerplate did it for them (and they were not removed).  That might result in performance issues (long term).

**Comment by serundeputy** [comment]
Updated and merged https://github.com/backdrop-contrib/drush/pull/160
It just generates a base `*.info` file and a `*.module` file with nothing but the opening `<?php` tag ... folks don't have to use it if they don't want to.

Perhaps in the future we can iterate and prompt if they hook_THIS or hook_THAT or whatever.
