### ISSUE TITLE
Support multisite setups

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#37]
When running `drush dl devel` from /backdrop/sites/[sitename] I get the following message:

> Success:  Project devel downloaded to /backdrop/modules/devel.

It should download to /backdrop/sites/[sitename]/modules instead.

----

PR @BWPanda https://github.com/backdrop-contrib/drush/pull/143

**Comment by serundeputy** [comment]
Thanks for the report @BWPanda!

I have little experience w/ multisite in Drupal and none in Backdrop 😦 So, It'll probably take me a while to get to this and setup a multisite to test against, but this is what I understand needs to happen here:
1.  Check where the user is executing the `drush dl` command from 
   Is it a generic location, or in `/backdrop/sites/[sitename]` if we are in `/backdrop/sites/[sitename]` then put the module in `/backdrop/sites/[sitename]/modules` otherwise proceed as normal.

**Comment by ghost** [comment]
Closing this as a duplicate of https://github.com/backdrop-contrib/drush/issues/15

**Comment by ghost** [comment]
Nope, sorry, not a duplicate of that issue (got confused).

**Comment by ghost** [comment]
This happens with `dl` and `up`. Basically this issue is a feature request to support multisite.

**Comment by ghost** [comment]
@serundeputy I agree with your idea of what needs to happen to make this work. I'd submit a PR myself, but I'm stuck on the first part: working out how to check where the user is executing the drush command from...

**Comment by ghost** [comment]
Added PR that fixes this (with my testing).

**Comment by ghost** [comment]
This is working, so closing this issue now...

**Comment by ghost** [comment]
Oi, this isn't fixed/committed yet, don't know what I was thinking...

**Comment by serundeputy** [comment]
thanks @BWPanda I've merged this and it will ship with `0.3.0`.
