### ISSUE TITLE
add support for `drush rn`

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#61]
This is one of my favorite features in Drush, letting it create release notes for you!  @quicksketch hates creating release notes, so we should find a way to use this handy tool for managing release notes easier for Backdrop (both core, and contrib) that are formatted how we need them over here:
- Markdown not HTML
- Link to GItHub not d.o
- etc

**Comment by serundeputy** [comment]
`PR` adds support for `drush rn`.

`drush rn 1.4.4 1.4.5 --md` will output changes between the `1.4.4` and `1.4.5` tags for example:

geoff@gspmbp backdrop (1.x) $ drush rn 1.4.4 1.4.5 --md
**Changes since 1.4.4**
- Backdrop 1.4.5
- [#2020](https://github.com/backdrop/backdrop-issues/issues/2020): Ensure rss.xml is outputting xml and not additional html.
- [#1918](https://github.com/backdrop/backdrop-issues/issues/1918): Add layout page title
- [#1373](https://github.com/backdrop/backdrop-issues/issues/1373): Add basic file usage saving to custom text blocks.
- [#1373](https://github.com/backdrop/backdrop-issues/issues/1373): Adding option for disabling uploads within editors on a per-field basis.
- [#2169](https://github.com/backdrop/backdrop-issues/issues/2169): Clear the "Operating in maintenance mode." message before showing the "The site is no longer in maintenance mode." message.
- [#1231](https://github.com/backdrop/backdrop-issues/issues/1231): Remove the anchor-flag button until we can get it working properly.
- [#2166](https://github.com/backdrop/backdrop-issues/issues/2166): Moving tabledrag handle to a theme function.
- [#1699](https://github.com/backdrop/backdrop-issues/issues/1699): Negative margins added to admin bar.
- [#2150](https://github.com/backdrop/backdrop-issues/issues/2150): Don't add classes to links within actions element.
- [#2142](https://github.com/backdrop/backdrop-issues/issues/2142): Fix Backdrop link/unlink plugin buttons.
- [#1699](https://github.com/backdrop/backdrop-issues/issues/1699): Make the notification badge round.
- [#2124](https://github.com/backdrop/backdrop-issues/issues/2124): [UX] Update button text for inserting an image into the rich-text editor.
- [#2135](https://github.com/backdrop/backdrop-issues/issues/2135): Remove console.log() calls.
- [#2083](https://github.com/backdrop/backdrop-issues/issues/2083): Follow-up to fix hidden visibility of the font checker.
- [#2123](https://github.com/backdrop/backdrop-issues/issues/2123): Date Formats textfield UI is difficult to type in (keeps getting disabled).
- [#2120](https://github.com/backdrop/backdrop-issues/issues/2120): Clean up Layout module PHP inspections.
- [#1931](https://github.com/backdrop/backdrop-issues/issues/1931): Layouts: empty .dropbutton-\* <divs>
- [#2109](https://github.com/backdrop/backdrop-issues/issues/2109): Canceling the deletion of a role redirects to the "Manage user accounts" page instead of back to "Roles" page.
- 1113:Disable display of author info & photo on basic pages.
-  Issue [#2016](https://github.com/backdrop/backdrop-issues/issues/2016): Remove the trailing dot from the "Browse available tokens." link.
- [#2023](https://github.com/backdrop/backdrop-issues/issues/2023): [UX] Use states to show/hide the "Files displayed by default" option for fields of type file.
- Fix gitignore patterns to only match webroot.
- Fix the pull columns in the Taylor Flipped layout.
- [#2110](https://github.com/backdrop/backdrop-issues/issues/2110): Show the "Machine name:" label for user roles?
- [#2083](https://github.com/backdrop/backdrop-issues/issues/2083): Fix responsive tabs issues. Split font checker into backdrop.js.
- [#1588](https://github.com/backdrop/backdrop-issues/issues/1588): Fix upgrade from Drupal by converting taxonomy_term_data table to InnoDB.
- [#2087](https://github.com/backdrop/backdrop-issues/issues/2087): Update docs on how to provide a new image style.
- [#2098](https://github.com/backdrop/backdrop-issues/issues/2098): Updated sticky table header to be more accurate.
- Reverting version string.

of course you can direct this output to a file: `drush rn 1.4.4 1.4.5 --md > my-release.md`

@jenlampton, @quicksketch give it a test.

thanks,
~Geoff

**Comment by jenlampton** [comment]
Yessssss!!!!!

**Comment by jenlampton** [comment]
@serundeputy this is fantastic! It looks like the only poorly formatted lines are caused by our poorly formatted commit messages, so RTBC from me :) and ty for the fast turnaround!!! :)

**Comment by serundeputy** [comment]
Thanks @jenlampton merged into `1.x-0.x` and will ship with `0.0.3`; of course using the HEAD of `1.x-0.x` makes the `rn` command available now.

thanks for testing!
Happy releasing!
